### ISSUE TITLE
how to open the data by matlab

### ISSUE THREAD

**Issue by panchanghui** [robintibor/high-gamma-dataset#3]
Although this data file is a mat file, it cannot be opened with MATLAB. 
I don't know why matlab can't open the mat file, so I want to ask how to convert these data into Matlab available data.
when I load 2.mat 
matlab say:Incorrect use of load

Unable to read mat file D: \ EEG program \ all data \ high gamma data \ 2.mat. Not a binary mat file. Try load - ASCII to read as text.

**Comment by leoeooe** [comment]
this is not the correct data. download it in https://gin.g-node.org/robintibor/high-gamma-dataset/src/master/data/train

**Comment by leoeooe** [comment]
the data you download is just 128kb

**Comment by robintibor** [comment]
So yeah just for others these are ways to use the data, in order of recommendation:
1) Use braindecode.org braindecode library, https://braindecode.org/stable/generated/braindecode.datasets.HGD.html High Gamma Dataset is included there
2) Using gin, https://gin.g-node.org/G-Node/Info/wiki since we are storing it in a gin repository.
Concretely, you would need to run
```bash
gin get robintibor/high-gamma-dataset
cd high-gamma-dataset
gin download --content
```

3) Download individual files manually, e.g., go on https://gin.g-node.org/robintibor/high-gamma-dataset/src/master/data/train/1.edf then right click on download-> save link as
